spring:
  application:
    name: airbnb

  profiles:
    active: dev
    # oauth2
    include: oauth

  # datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${datasource.url}
    username: ${datasource.user}
    password: ${datasource.pwd}

  # ddl-auto
  jpa:
    hibernate:
      ddl-auto: ${ddl-auto} # create create-drop update validate none(default/ on production)

    properties:
      hibernate:
        show_sql: ${show-sql}
        format_sql: ${format-sql}
      dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect

    # data.sql operate after hibernate init (not on production)
    defer-datasource-initialization: ${defer-datasource-initialization}

  # sql init (not on production)
  sql:
    init:
      mode: ${sql-init-mode}

# Logging level
logging:
  level:
    com:
      airbnb: debug

# url prefix
server:
  servlet:
    context-path: ${url-prefix}

cors:
  originUrl: ${cors-originUrl}

jwt:
  access-token:
    secret: ${jwt-access-token.secret}
    expiration: ${jwt-access-token.expiration}