name: CI

on:
  push:
<<<<<<< HEAD
    branches: [ "dev-be" ]
  pull_request:
    branches: [ "dev-be" ]
=======
    branches: [ "actions" ]
  pull_request:
    branches: [ "actions" ]
>>>>>>> fb84213 (ğŸ› fix: github actions ë””ë ‰í† ë¦¬ ì´ë¦„ ì˜¤íƒ€ ìˆ˜ì •)

permissions:
  contents: read  # ì´ ì„¤ì •ì€ ì›Œí¬í”Œë¡œìš°ê°€ ë¦¬í¬ì§€í† ë¦¬ì˜ ì½˜í…ì¸ ë¥¼ ì½ì„ ìˆ˜ ìˆë„ë¡ í—ˆìš©í•©ë‹ˆë‹¤.


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: "corretto"
     
    - name: Build with Gradle
      run: |
            chmod +x ./airdnb/gradlew
            cd ./airdnb
            ./gradlew clean build -x test
    - name: Docker build & push to docker repo
      run: |
            echo ${{ secrets.CORI_DOCKER_TOKEN }} | docker login -u ${{ secrets.CORI_DOCKER_USERNAME }} --password-stdin
            cd ./airdnb
            docker build -f ./Dockerfile -t ${{ secrets.CORI_DOCKER_REPO }} .
            docker push ${{ secrets.CORI_DOCKER_REPO }}

  deploy:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    needs: build

    steps:
=======
    
    steps:
    - name: Build with Gradle
      run: |
            chmod +x ./airdnb/gradlew
            cd ./airdnb
            ./gradlew clean build -x test
    - name: Docker build & push to docker repo
      run: |
            echo ${{ secrets.CORI_DOCKER_TOKEN }} | docker login -u ${{ secrets.CORI_DOCKER_USERNAME }} --password-stdin
            cd ./airdnb/
            docker build -f ./Dockerfile -t ${{ secrets.CORI_DOCKER_REPO }} .
            docker push ${{ secrets.CORI_DOCKER_REPO }}
>>>>>>> fb84213 (ğŸ› fix: github actions ë””ë ‰í† ë¦¬ ì´ë¦„ ì˜¤íƒ€ ìˆ˜ì •)
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
<<<<<<< HEAD
        key: ${{ secrets.CORI_PRIVATE_KEY }}
=======
        key: ${{ secrets.PRIVATE_KEY }}
>>>>>>> fb84213 (ğŸ› fix: github actions ë””ë ‰í† ë¦¬ ì´ë¦„ ì˜¤íƒ€ ìˆ˜ì •)
        script: |
          sudo docker rm -f $(sudo docker ps -qa)
          sudo docker pull ${{ secrets.CORI_DOCKER_REPO }}
          sudo docker-compose up -d
          sudo docker image prune -f
